
// Objective-C API for talking to the following Go packages
//
//	github.com/cmanus/GoExcite/Golang
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GoExcite_FRAMEWORK_H__
#define __GoExcite_FRAMEWORK_H__

#include "GoExcite.objc.h"
#include "Universe.objc.h"

#endif
